

EXPLICIT_SYMBOL(cpc_Creer_Contexte)
EXPLICIT_SYMBOL(cpc_Obtenir_Zone_Contexte)
EXPLICIT_SYMBOL(cpc_Blitter)
EXPLICIT_SYMBOL(cpc_CCP_Exec_Commande)
EXPLICIT_SYMBOL(cpc_CCP_Exec_Thread_cpc)
EXPLICIT_SYMBOL(cpc_Exec_en_cours)

EXPLICIT_SYMBOL(cpc_cpinti_debug_cpinticore)

EXPLICIT_SYMBOL(cpc_cpinti_debug_plus_cpinticore)

EXPLICIT_SYMBOL(cpc_cpinti_Fichier_Existe)
EXPLICIT_SYMBOL(cpc_cpinti_Taille_Fichier)
EXPLICIT_SYMBOL(cpc_cpinti_Lire_Fichier_complet)


EXPLICIT_SYMBOL(cpc_cpinti_sleep_us)
EXPLICIT_SYMBOL(cpc_cpinti_sleep_ms)
EXPLICIT_SYMBOL(cpc_cpinti_sleep_sec)
EXPLICIT_SYMBOL(cpc_cpinti_Obtenir_Temps_ms)
