gpp @a -c _Demo\Demo.cpp -o ..\obj\llvm_Demo.obj
gpp @a -c _Demo\JitProg.cpp -o ..\obj\llvm_JitProg.obj
gpp @a -c src\lib\An\AliasAnalysis.cpp -o ..\obj\AliasAnalysis.obj
gpp @a -c src\lib\An\AliasAnalysisEvaluator.cpp -o ..\obj\AliasAnalysisEvaluator.obj
gpp @a -c src\lib\An\AliasSetTracker.cpp -o ..\obj\AliasSetTracker.obj
gpp @a -c src\lib\An\Analysis.cpp -o ..\obj\Analysis.obj
gpp @a -c src\lib\An\AssumptionCache.cpp -o ..\obj\AssumptionCache.obj
gpp @a -c src\lib\An\BasicAliasAnalysis.cpp -o ..\obj\BasicAliasAnalysis.obj
gpp @a -c src\lib\An\BlockFrequencyInfo.cpp -o ..\obj\BlockFrequencyInfo.obj
gpp @a -c src\lib\An\BlockFrequencyInfoImpl.cpp -o ..\obj\BlockFrequencyInfoImpl.obj
gpp @a -c src\lib\An\BranchProbabilityInfo.cpp -o ..\obj\BranchProbabilityInfo.obj
gpp @a -c src\lib\An\CallGraph.cpp -o ..\obj\CallGraph.obj
gpp @a -c src\lib\An\CallGraphSCCPass.cpp -o ..\obj\CallGraphSCCPass.obj
gpp @a -c src\lib\An\CallPrinter.cpp -o ..\obj\CallPrinter.obj
gpp @a -c src\lib\An\CaptureTracking.cpp -o ..\obj\CaptureTracking.obj
gpp @a -c src\lib\An\CFG.cpp -o ..\obj\CFG.obj
gpp @a -c src\lib\An\CFGPrinter.cpp -o ..\obj\CFGPrinter.obj
gpp @a -c src\lib\An\CFLAliasAnalysis.cpp -o ..\obj\CFLAliasAnalysis.obj
gpp @a -c src\lib\An\CGSCCPassManager.cpp -o ..\obj\CGSCCPassManager.obj
gpp @a -c src\lib\An\CodeMetrics.cpp -o ..\obj\CodeMetrics.obj
gpp @a -c src\lib\An\ConstantFolding.cpp -o ..\obj\ConstantFolding.obj
gpp @a -c src\lib\An\CostModel.cpp -o ..\obj\CostModel.obj
gpp @a -c src\lib\An\Delinearization.cpp -o ..\obj\Delinearization.obj
gpp @a -c src\lib\An\DemandedBits.cpp -o ..\obj\DemandedBits.obj
gpp @a -c src\lib\An\DependenceAnalysis.cpp -o ..\obj\DependenceAnalysis.obj
gpp @a -c src\lib\An\DivergenceAnalysis.cpp -o ..\obj\DivergenceAnalysis.obj
gpp @a -c src\lib\An\DominanceFrontier.cpp -o ..\obj\DominanceFrontier.obj
gpp @a -c src\lib\An\DomPrinter.cpp -o ..\obj\DomPrinter.obj
gpp @a -c src\lib\An\EHPersonalities.cpp -o ..\obj\EHPersonalities.obj
gpp @a -c src\lib\An\GlobalsModRef.cpp -o ..\obj\GlobalsModRef.obj
gpp @a -c src\lib\An\InlineCost.cpp -o ..\obj\InlineCost.obj
gpp @a -c src\lib\An\InstCount.cpp -o ..\obj\InstCount.obj
gpp @a -c src\lib\An\InstructionSimplify.cpp -o ..\obj\InstructionSimplify.obj
gpp @a -c src\lib\An\Interval.cpp -o ..\obj\Interval.obj
gpp @a -c src\lib\An\IntervalPartition.cpp -o ..\obj\IntervalPartition.obj
gpp @a -c src\lib\An\IteratedDominanceFrontier.cpp -o ..\obj\IteratedDominanceFrontier.obj
gpp @a -c src\lib\An\IVUsers.cpp -o ..\obj\IVUsers.obj
gpp @a -c src\lib\An\LazyCallGraph.cpp -o ..\obj\LazyCallGraph.obj
gpp @a -c src\lib\An\LazyValueInfo.cpp -o ..\obj\LazyValueInfo.obj
gpp @a -c src\lib\An\Lint.cpp -o ..\obj\Lint.obj
gpp @a -c src\lib\An\Loads.cpp -o ..\obj\Loads.obj
gpp @a -c src\lib\An\LoopAccessAnalysis.cpp -o ..\obj\LoopAccessAnalysis.obj
gpp @a -c src\lib\An\LoopInfo.cpp -o ..\obj\LoopInfo.obj
gpp @a -c src\lib\An\LoopPass.cpp -o ..\obj\LoopPass.obj
gpp @a -c src\lib\An\MemDepPrinter.cpp -o ..\obj\MemDepPrinter.obj
gpp @a -c src\lib\An\MemDerefPrinter.cpp -o ..\obj\MemDerefPrinter.obj
gpp @a -c src\lib\An\MemoryBuiltins.cpp -o ..\obj\MemoryBuiltins.obj
gpp @a -c src\lib\An\MemoryDependenceAnalysis.cpp -o ..\obj\MemoryDependenceAnalysis.obj
gpp @a -c src\lib\An\MemoryLocation.cpp -o ..\obj\MemoryLocation.obj
gpp @a -c src\lib\An\ModuleDebugInfoPrinter.cpp -o ..\obj\ModuleDebugInfoPrinter.obj
gpp @a -c src\lib\An\ObjCARCAliasAnalysis.cpp -o ..\obj\ObjCARCAliasAnalysis.obj
gpp @a -c src\lib\An\ObjCARCAnalysisUtils.cpp -o ..\obj\ObjCARCAnalysisUtils.obj
gpp @a -c src\lib\An\ObjCARCInstKind.cpp -o ..\obj\ObjCARCInstKind.obj
gpp @a -c src\lib\An\OrderedBasicBlock.cpp -o ..\obj\OrderedBasicBlock.obj
gpp @a -c src\lib\An\PHITransAddr.cpp -o ..\obj\PHITransAddr.obj
gpp @a -c src\lib\An\PostDominators.cpp -o ..\obj\PostDominators.obj
gpp @a -c src\lib\An\PtrUseVisitor.cpp -o ..\obj\PtrUseVisitor.obj
gpp @a -c src\lib\An\RegionInfo.cpp -o ..\obj\RegionInfo.obj
gpp @a -c src\lib\An\RegionPass.cpp -o ..\obj\RegionPass.obj
gpp @a -c src\lib\An\RegionPrinter.cpp -o ..\obj\RegionPrinter.obj
gpp @a -c src\lib\An\ScalarEvolution.cpp -o ..\obj\ScalarEvolution.obj
gpp @a -c src\lib\An\ScalarEvolutionAliasAnalysis.cpp -o ..\obj\ScalarEvolutionAliasAnalysis.obj
gpp @a -c src\lib\An\ScalarEvolutionExpander.cpp -o ..\obj\ScalarEvolutionExpander.obj
gpp @a -c src\lib\An\ScalarEvolutionNormalization.cpp -o ..\obj\ScalarEvolutionNormalization.obj
gpp @a -c src\lib\An\ScopedNoAliasAA.cpp -o ..\obj\ScopedNoAliasAA.obj
gpp @a -c src\lib\An\SparsePropagation.cpp -o ..\obj\SparsePropagation.obj
gpp @a -c src\lib\An\TargetLibraryInfo.cpp -o ..\obj\TargetLibraryInfo.obj
gpp @a -c src\lib\An\TargetTransformInfo.cpp -o ..\obj\TargetTransformInfo.obj
gpp @a -c src\lib\An\Trace.cpp -o ..\obj\Trace.obj
gpp @a -c src\lib\An\TypeBasedAliasAnalysis.cpp -o ..\obj\TypeBasedAliasAnalysis.obj
gpp @a -c src\lib\An\ValueTracking.cpp -o ..\obj\ValueTracking.obj
gpp @a -c src\lib\An\VectorUtils.cpp -o ..\obj\VectorUtils.obj
gpp @a -c src\lib\AsmParser\LLLexer.cpp -o ..\obj\LLLexer.obj
gpp @a -c src\lib\AsmParser\LLParser.cpp -o ..\obj\LLParser.obj
gpp @a -c src\lib\AsmParser\Parser.cpp -o ..\obj\Parser.obj
gpp @a -c src\lib\Bitcode\Reader\BitcodeReader.cpp -o ..\obj\BitcodeReader.obj
gpp @a -c src\lib\Bitcode\Reader\BitReader.cpp -o ..\obj\BitReader.obj
gpp @a -c src\lib\Bitcode\Reader\BitstreamReader.cpp -o ..\obj\BitstreamReader.obj
gpp @a -c src\lib\Bitcode\Writer\BitcodeWriter.cpp -o ..\obj\BitcodeWriter.obj
gpp @a -c src\lib\Bitcode\Writer\BitcodeWriterPass.cpp -o ..\obj\BitcodeWriterPass.obj
gpp @a -c src\lib\Bitcode\Writer\BitWriter.cpp -o ..\obj\BitWriter.obj
gpp @a -c src\lib\Bitcode\Writer\ValueEnumerator.cpp -o ..\obj\ValueEnumerator.obj
gpp @a -c src\lib\CG\AggressiveAntiDepBreaker.cpp -o ..\obj\AggressiveAntiDepBreaker.obj
gpp @a -c src\lib\CG\AllocationOrder.cpp -o ..\obj\AllocationOrder.obj
gpp @a -c src\lib\CG\Analysis.cpp -o ..\obj\Analysis_2.obj
gpp @a -c src\lib\CG\AsmPrinter\AddressPool.cpp -o ..\obj\AddressPool.obj
gpp @a -c src\lib\CG\AsmPrinter\ARMException.cpp -o ..\obj\ARMException.obj
gpp @a -c src\lib\CG\AsmPrinter\AsmPrinter.cpp -o ..\obj\AsmPrinter.obj
gpp @a -c src\lib\CG\AsmPrinter\AsmPrinterDwarf.cpp -o ..\obj\AsmPrinterDwarf.obj
gpp @a -c src\lib\CG\AsmPrinter\AsmPrinterInlineAsm.cpp -o ..\obj\AsmPrinterInlineAsm.obj
gpp @a -c src\lib\CG\AsmPrinter\DbgValueHistoryCalculator.cpp -o ..\obj\DbgValueHistoryCalculator.obj
gpp @a -c src\lib\CG\AsmPrinter\DebugLocStream.cpp -o ..\obj\DebugLocStream.obj
gpp @a -c src\lib\CG\AsmPrinter\DIE.cpp -o ..\obj\DIE.obj
gpp @a -c src\lib\CG\AsmPrinter\DIEHash.cpp -o ..\obj\DIEHash.obj
gpp @a -c src\lib\CG\AsmPrinter\DwarfAccelTable.cpp -o ..\obj\DwarfAccelTable.obj
gpp @a -c src\lib\CG\AsmPrinter\DwarfCFIException.cpp -o ..\obj\DwarfCFIException.obj
gpp @a -c src\lib\CG\AsmPrinter\DwarfCompileUnit.cpp -o ..\obj\DwarfCompileUnit.obj
gpp @a -c src\lib\CG\AsmPrinter\DwarfDebug.cpp -o ..\obj\DwarfDebug.obj
gpp @a -c src\lib\CG\AsmPrinter\DwarfExpression.cpp -o ..\obj\DwarfExpression.obj
gpp @a -c src\lib\CG\AsmPrinter\DwarfFile.cpp -o ..\obj\DwarfFile.obj
gpp @a -c src\lib\CG\AsmPrinter\DwarfStringPool.cpp -o ..\obj\DwarfStringPool.obj
gpp @a -c src\lib\CG\AsmPrinter\DwarfUnit.cpp -o ..\obj\DwarfUnit.obj
gpp @a -c src\lib\CG\AsmPrinter\EHStreamer.cpp -o ..\obj\EHStreamer.obj
gpp @a -c src\lib\CG\AsmPrinter\ErlangGCPrinter.cpp -o ..\obj\ErlangGCPrinter.obj
gpp @a -c src\lib\CG\AsmPrinter\OcamlGCPrinter.cpp -o ..\obj\OcamlGCPrinter.obj
gpp @a -c src\lib\CG\AsmPrinter\WinCodeViewLineTables.cpp -o ..\obj\WinCodeViewLineTables.obj
gpp @a -c src\lib\CG\AsmPrinter\WinException.cpp -o ..\obj\WinException.obj
gpp @a -c src\lib\CG\AtomicExpandPass.cpp -o ..\obj\AtomicExpandPass.obj
gpp @a -c src\lib\CG\BasicTargetTransformInfo.cpp -o ..\obj\BasicTargetTransformInfo.obj
gpp @a -c src\lib\CG\BranchFolding.cpp -o ..\obj\BranchFolding.obj
gpp @a -c src\lib\CG\CalcSpillWeights.cpp -o ..\obj\CalcSpillWeights.obj
gpp @a -c src\lib\CG\CallingConvLower.cpp -o ..\obj\CallingConvLower.obj
gpp @a -c src\lib\CG\CodeGen.cpp -o ..\obj\CodeGen.obj
gpp @a -c src\lib\CG\CodeGenPrepare.cpp -o ..\obj\CodeGenPrepare.obj
gpp @a -c src\lib\CG\CoreCLRGC.cpp -o ..\obj\CoreCLRGC.obj
gpp @a -c src\lib\CG\CriticalAntiDepBreaker.cpp -o ..\obj\CriticalAntiDepBreaker.obj
gpp @a -c src\lib\CG\DeadMachineInstructionElim.cpp -o ..\obj\DeadMachineInstructionElim.obj
gpp @a -c src\lib\CG\DFAPacketizer.cpp -o ..\obj\DFAPacketizer.obj
gpp @a -c src\lib\CG\DwarfEHPrepare.cpp -o ..\obj\DwarfEHPrepare.obj
gpp @a -c src\lib\CG\EarlyIfConversion.cpp -o ..\obj\EarlyIfConversion.obj
gpp @a -c src\lib\CG\EdgeBundles.cpp -o ..\obj\EdgeBundles.obj
gpp @a -c src\lib\CG\ErlangGC.cpp -o ..\obj\ErlangGC.obj
gpp @a -c src\lib\CG\ExecutionDepsFix.cpp -o ..\obj\ExecutionDepsFix.obj
gpp @a -c src\lib\CG\ExpandISelPseudos.cpp -o ..\obj\ExpandISelPseudos.obj
gpp @a -c src\lib\CG\ExpandPostRAPseudos.cpp -o ..\obj\ExpandPostRAPseudos.obj
gpp @a -c src\lib\CG\FaultMaps.cpp -o ..\obj\FaultMaps.obj
gpp @a -c src\lib\CG\FuncletLayout.cpp -o ..\obj\FuncletLayout.obj
gpp @a -c src\lib\CG\GCMetadata.cpp -o ..\obj\GCMetadata.obj
gpp @a -c src\lib\CG\GCMetadataPrinter.cpp -o ..\obj\GCMetadataPrinter.obj
gpp @a -c src\lib\CG\GCRootLowering.cpp -o ..\obj\GCRootLowering.obj
gpp @a -c src\lib\CG\GCStrategy.cpp -o ..\obj\GCStrategy.obj
gpp @a -c src\lib\CG\GlobalMerge.cpp -o ..\obj\GlobalMerge.obj
gpp @a -c src\lib\CG\IfConversion.cpp -o ..\obj\IfConversion.obj
gpp @a -c src\lib\CG\ImplicitNullChecks.cpp -o ..\obj\ImplicitNullChecks.obj
gpp @a -c src\lib\CG\InlineSpiller.cpp -o ..\obj\InlineSpiller.obj
gpp @a -c src\lib\CG\InterferenceCache.cpp -o ..\obj\InterferenceCache.obj
gpp @a -c src\lib\CG\InterleavedAccessPass.cpp -o ..\obj\InterleavedAccessPass.obj
gpp @a -c src\lib\CG\IntrinsicLowering.cpp -o ..\obj\IntrinsicLowering.obj
gpp @a -c src\lib\CG\LatencyPriorityQueue.cpp -o ..\obj\LatencyPriorityQueue.obj
gpp @a -c src\lib\CG\LexicalScopes.cpp -o ..\obj\LexicalScopes.obj
gpp @a -c src\lib\CG\LiveDebugValues.cpp -o ..\obj\LiveDebugValues.obj
gpp @a -c src\lib\CG\LiveDebugVariables.cpp -o ..\obj\LiveDebugVariables.obj
gpp @a -c src\lib\CG\LiveInterval.cpp -o ..\obj\LiveInterval.obj
gpp @a -c src\lib\CG\LiveIntervalAnalysis.cpp -o ..\obj\LiveIntervalAnalysis.obj
gpp @a -c src\lib\CG\LiveIntervalUnion.cpp -o ..\obj\LiveIntervalUnion.obj
gpp @a -c src\lib\CG\LivePhysRegs.cpp -o ..\obj\LivePhysRegs.obj
gpp @a -c src\lib\CG\LiveRangeCalc.cpp -o ..\obj\LiveRangeCalc.obj
gpp @a -c src\lib\CG\LiveRangeEdit.cpp -o ..\obj\LiveRangeEdit.obj
gpp @a -c src\lib\CG\LiveRegMatrix.cpp -o ..\obj\LiveRegMatrix.obj
gpp @a -c src\lib\CG\LiveStackAnalysis.cpp -o ..\obj\LiveStackAnalysis.obj
gpp @a -c src\lib\CG\LiveVariables.cpp -o ..\obj\LiveVariables.obj
gpp @a -c src\lib\CG\LLVMTargetMachine.cpp -o ..\obj\LLVMTargetMachine.obj
gpp @a -c src\lib\CG\LocalStackSlotAllocation.cpp -o ..\obj\LocalStackSlotAllocation.obj
gpp @a -c src\lib\CG\MachineBasicBlock.cpp -o ..\obj\MachineBasicBlock.obj
gpp @a -c src\lib\CG\MachineBlockFrequencyInfo.cpp -o ..\obj\MachineBlockFrequencyInfo.obj
gpp @a -c src\lib\CG\MachineBlockPlacement.cpp -o ..\obj\MachineBlockPlacement.obj
gpp @a -c src\lib\CG\MachineBranchProbabilityInfo.cpp -o ..\obj\MachineBranchProbabilityInfo.obj
gpp @a -c src\lib\CG\MachineCombiner.cpp -o ..\obj\MachineCombiner.obj
gpp @a -c src\lib\CG\MachineCopyPropagation.cpp -o ..\obj\MachineCopyPropagation.obj
gpp @a -c src\lib\CG\MachineCSE.cpp -o ..\obj\MachineCSE.obj
gpp @a -c src\lib\CG\MachineDominanceFrontier.cpp -o ..\obj\MachineDominanceFrontier.obj
gpp @a -c src\lib\CG\MachineDominators.cpp -o ..\obj\MachineDominators.obj
gpp @a -c src\lib\CG\MachineFunction.cpp -o ..\obj\MachineFunction.obj
gpp @a -c src\lib\CG\MachineFunctionAnalysis.cpp -o ..\obj\MachineFunctionAnalysis.obj
gpp @a -c src\lib\CG\MachineFunctionPass.cpp -o ..\obj\MachineFunctionPass.obj
gpp @a -c src\lib\CG\MachineFunctionPrinterPass.cpp -o ..\obj\MachineFunctionPrinterPass.obj
gpp @a -c src\lib\CG\MachineInstr.cpp -o ..\obj\MachineInstr.obj
gpp @a -c src\lib\CG\MachineInstrBundle.cpp -o ..\obj\MachineInstrBundle.obj
gpp @a -c src\lib\CG\MachineLICM.cpp -o ..\obj\MachineLICM.obj
gpp @a -c src\lib\CG\MachineLoopInfo.cpp -o ..\obj\MachineLoopInfo.obj
gpp @a -c src\lib\CG\MachineModuleInfo.cpp -o ..\obj\MachineModuleInfo.obj
gpp @a -c src\lib\CG\MachineModuleInfoImpls.cpp -o ..\obj\MachineModuleInfoImpls.obj
gpp @a -c src\lib\CG\MachinePassRegistry.cpp -o ..\obj\MachinePassRegistry.obj
gpp @a -c src\lib\CG\MachinePostDominators.cpp -o ..\obj\MachinePostDominators.obj
gpp @a -c src\lib\CG\MachineRegionInfo.cpp -o ..\obj\MachineRegionInfo.obj
gpp @a -c src\lib\CG\MachineRegisterInfo.cpp -o ..\obj\MachineRegisterInfo.obj
gpp @a -c src\lib\CG\MachineScheduler.cpp -o ..\obj\MachineScheduler.obj
gpp @a -c src\lib\CG\MachineSink.cpp -o ..\obj\MachineSink.obj
gpp @a -c src\lib\CG\MachineSSAUpdater.cpp -o ..\obj\MachineSSAUpdater.obj
gpp @a -c src\lib\CG\MachineTraceMetrics.cpp -o ..\obj\MachineTraceMetrics.obj
gpp @a -c src\lib\CG\MachineVerifier.cpp -o ..\obj\MachineVerifier.obj
gpp @a -c src\lib\CG\MIRPrinter.cpp -o ..\obj\MIRPrinter.obj
gpp @a -c src\lib\CG\MIRPrintingPass.cpp -o ..\obj\MIRPrintingPass.obj
gpp @a -c src\lib\CG\OcamlGC.cpp -o ..\obj\OcamlGC.obj
gpp @a -c src\lib\CG\OptimizePHIs.cpp -o ..\obj\OptimizePHIs.obj
gpp @a -c src\lib\CG\ParallelCG.cpp -o ..\obj\ParallelCG.obj
gpp @a -c src\lib\CG\Passes.cpp -o ..\obj\Passes.obj
gpp @a -c src\lib\CG\PeepholeOptimizer.cpp -o ..\obj\PeepholeOptimizer.obj
gpp @a -c src\lib\CG\PHIElimination.cpp -o ..\obj\PHIElimination.obj
gpp @a -c src\lib\CG\PHIEliminationUtils.cpp -o ..\obj\PHIEliminationUtils.obj
gpp @a -c src\lib\CG\PostRASchedulerList.cpp -o ..\obj\PostRASchedulerList.obj
gpp @a -c src\lib\CG\ProcessImplicitDefs.cpp -o ..\obj\ProcessImplicitDefs.obj
gpp @a -c src\lib\CG\PrologEpilogInserter.cpp -o ..\obj\PrologEpilogInserter.obj
gpp @a -c src\lib\CG\PseudoSourceValue.cpp -o ..\obj\PseudoSourceValue.obj
gpp @a -c src\lib\CG\RegAllocBase.cpp -o ..\obj\RegAllocBase.obj
gpp @a -c src\lib\CG\RegAllocBasic.cpp -o ..\obj\RegAllocBasic.obj
gpp @a -c src\lib\CG\RegAllocFast.cpp -o ..\obj\RegAllocFast.obj
gpp @a -c src\lib\CG\RegAllocGreedy.cpp -o ..\obj\RegAllocGreedy.obj
gpp @a -c src\lib\CG\RegAllocPBQP.cpp -o ..\obj\RegAllocPBQP.obj
gpp @a -c src\lib\CG\RegisterClassInfo.cpp -o ..\obj\RegisterClassInfo.obj
gpp @a -c src\lib\CG\RegisterCoalescer.cpp -o ..\obj\RegisterCoalescer.obj
gpp @a -c src\lib\CG\RegisterPressure.cpp -o ..\obj\RegisterPressure.obj
gpp @a -c src\lib\CG\RegisterScavenging.cpp -o ..\obj\RegisterScavenging.obj
gpp @a -c src\lib\CG\ScheduleDAG.cpp -o ..\obj\ScheduleDAG.obj
gpp @a -c src\lib\CG\ScheduleDAGInstrs.cpp -o ..\obj\ScheduleDAGInstrs.obj
gpp @a -c src\lib\CG\ScheduleDAGPrinter.cpp -o ..\obj\ScheduleDAGPrinter.obj
gpp @a -c src\lib\CG\ScoreboardHazardRecognizer.cpp -o ..\obj\ScoreboardHazardRecognizer.obj
gpp @a -c src\lib\CG\SelectionDAG\DAGCombiner.cpp -o ..\obj\DAGCombiner.obj
gpp @a -c src\lib\CG\SelectionDAG\FastISel.cpp -o ..\obj\FastISel.obj
gpp @a -c src\lib\CG\SelectionDAG\FunctionLoweringInfo.cpp -o ..\obj\FunctionLoweringInfo.obj
gpp @a -c src\lib\CG\SelectionDAG\InstrEmitter.cpp -o ..\obj\InstrEmitter.obj
gpp @a -c src\lib\CG\SelectionDAG\LegalizeDAG.cpp -o ..\obj\LegalizeDAG.obj
gpp @a -c src\lib\CG\SelectionDAG\LegalizeFloatTypes.cpp -o ..\obj\LegalizeFloatTypes.obj
gpp @a -c src\lib\CG\SelectionDAG\LegalizeIntegerTypes.cpp -o ..\obj\LegalizeIntegerTypes.obj
gpp @a -c src\lib\CG\SelectionDAG\LegalizeTypes.cpp -o ..\obj\LegalizeTypes.obj
gpp @a -c src\lib\CG\SelectionDAG\LegalizeTypesGeneric.cpp -o ..\obj\LegalizeTypesGeneric.obj
gpp @a -c src\lib\CG\SelectionDAG\LegalizeVectorOps.cpp -o ..\obj\LegalizeVectorOps.obj
gpp @a -c src\lib\CG\SelectionDAG\LegalizeVectorTypes.cpp -o ..\obj\LegalizeVectorTypes.obj
gpp @a -c src\lib\CG\SelectionDAG\ResourcePriorityQueue.cpp -o ..\obj\ResourcePriorityQueue.obj
gpp @a -c src\lib\CG\SelectionDAG\ScheduleDAGFast.cpp -o ..\obj\ScheduleDAGFast.obj
gpp @a -c src\lib\CG\SelectionDAG\ScheduleDAGRRList.cpp -o ..\obj\ScheduleDAGRRList.obj
gpp @a -c src\lib\CG\SelectionDAG\ScheduleDAGSDNodes.cpp -o ..\obj\ScheduleDAGSDNodes.obj
gpp @a -c src\lib\CG\SelectionDAG\ScheduleDAGVLIW.cpp -o ..\obj\ScheduleDAGVLIW.obj
gpp @a -c src\lib\CG\SelectionDAG\SelectionDAG.cpp -o ..\obj\SelectionDAG.obj
gpp @a -c src\lib\CG\SelectionDAG\SelectionDAGBuilder.cpp -o ..\obj\SelectionDAGBuilder.obj
gpp @a -c src\lib\CG\SelectionDAG\SelectionDAGDumper.cpp -o ..\obj\SelectionDAGDumper.obj
gpp @a -c src\lib\CG\SelectionDAG\SelectionDAGISel.cpp -o ..\obj\SelectionDAGISel.obj
gpp @a -c src\lib\CG\SelectionDAG\SelectionDAGPrinter.cpp -o ..\obj\SelectionDAGPrinter.obj
gpp @a -c src\lib\CG\SelectionDAG\StatepointLowering.cpp -o ..\obj\StatepointLowering.obj
gpp @a -c src\lib\CG\SelectionDAG\TargetLowering.cpp -o ..\obj\TargetLowering.obj
gpp @a -c src\lib\CG\SelectionDAG\TargetSelectionDAGInfo.cpp -o ..\obj\TargetSelectionDAGInfo.obj
gpp @a -c src\lib\CG\ShadowStackGC.cpp -o ..\obj\ShadowStackGC.obj
gpp @a -c src\lib\CG\ShadowStackGCLowering.cpp -o ..\obj\ShadowStackGCLowering.obj
gpp @a -c src\lib\CG\ShrinkWrap.cpp -o ..\obj\ShrinkWrap.obj
gpp @a -c src\lib\CG\SjLjEHPrepare.cpp -o ..\obj\SjLjEHPrepare.obj
gpp @a -c src\lib\CG\SlotIndexes.cpp -o ..\obj\SlotIndexes.obj
gpp @a -c src\lib\CG\SpillPlacement.cpp -o ..\obj\SpillPlacement.obj
gpp @a -c src\lib\CG\SplitKit.cpp -o ..\obj\SplitKit.obj
gpp @a -c src\lib\CG\StackColoring.cpp -o ..\obj\StackColoring.obj
gpp @a -c src\lib\CG\StackMapLivenessAnalysis.cpp -o ..\obj\StackMapLivenessAnalysis.obj
gpp @a -c src\lib\CG\StackMaps.cpp -o ..\obj\StackMaps.obj
gpp @a -c src\lib\CG\StackProtector.cpp -o ..\obj\StackProtector.obj
gpp @a -c src\lib\CG\StackSlotColoring.cpp -o ..\obj\StackSlotColoring.obj
gpp @a -c src\lib\CG\StatepointExampleGC.cpp -o ..\obj\StatepointExampleGC.obj
gpp @a -c src\lib\CG\TailDuplication.cpp -o ..\obj\TailDuplication.obj
gpp @a -c src\lib\CG\TargetFrameLoweringImpl.cpp -o ..\obj\TargetFrameLoweringImpl.obj
gpp @a -c src\lib\CG\TargetInstrInfo.cpp -o ..\obj\TargetInstrInfo.obj
gpp @a -c src\lib\CG\TargetLoweringBase.cpp -o ..\obj\TargetLoweringBase.obj
gpp @a -c src\lib\CG\TargetLoweringObjectFileImpl.cpp -o ..\obj\TargetLoweringObjectFileImpl.obj
gpp @a -c src\lib\CG\TargetOptionsImpl.cpp -o ..\obj\TargetOptionsImpl.obj
gpp @a -c src\lib\CG\TargetRegisterInfo.cpp -o ..\obj\TargetRegisterInfo.obj
gpp @a -c src\lib\CG\TargetSchedule.cpp -o ..\obj\TargetSchedule.obj
gpp @a -c src\lib\CG\TwoAddressInstructionPass.cpp -o ..\obj\TwoAddressInstructionPass.obj
gpp @a -c src\lib\CG\UnreachableBlockElim.cpp -o ..\obj\UnreachableBlockElim.obj
gpp @a -c src\lib\CG\VirtRegMap.cpp -o ..\obj\VirtRegMap.obj
gpp @a -c src\lib\CG\WinEHPrepare.cpp -o ..\obj\WinEHPrepare.obj
gpp @a -c src\lib\EE\ExecutionEngine.cpp -o ..\obj\ExecutionEngine.obj
gpp @a -c src\lib\EE\ExecutionEngineBindings.cpp -o ..\obj\ExecutionEngineBindings.obj
gpp @a -c src\lib\EE\GDBRegistrationListener.cpp -o ..\obj\GDBRegistrationListener.obj
gpp @a -c src\lib\EE\Interpreter\Execution.cpp -o ..\obj\Execution.obj
gpp @a -c src\lib\EE\Interpreter\ExternalFunctions.cpp -o ..\obj\ExternalFunctions.obj
gpp @a -c src\lib\EE\Interpreter\Interpreter.cpp -o ..\obj\Interpreter.obj
gpp @a -c src\lib\EE\MCJIT\MCJIT.cpp -o ..\obj\MCJIT.obj
gpp @a -c src\lib\EE\Orc\ExecutionUtils.cpp -o ..\obj\ExecutionUtils.obj
gpp @a -c src\lib\EE\Orc\IndirectionUtils.cpp -o ..\obj\IndirectionUtils.obj
gpp @a -c src\lib\EE\Orc\NullResolver.cpp -o ..\obj\NullResolver.obj
gpp @a -c src\lib\EE\Orc\OrcArchitectureSupport.cpp -o ..\obj\OrcArchitectureSupport.obj
gpp @a -c src\lib\EE\Orc\OrcCBindings.cpp -o ..\obj\OrcCBindings.obj
gpp @a -c src\lib\EE\Orc\OrcCBindingsStack.cpp -o ..\obj\OrcCBindingsStack.obj
gpp @a -c src\lib\EE\Orc\OrcError.cpp -o ..\obj\OrcError.obj
gpp @a -c src\lib\EE\Orc\OrcMCJITReplacement.cpp -o ..\obj\OrcMCJITReplacement.obj
gpp @a -c src\lib\EE\Orc\OrcRemoteTargetRPCAPI.cpp -o ..\obj\OrcRemoteTargetRPCAPI.obj
gpp @a -c src\lib\EE\RuntimeDyld\RTDyldMemoryManager.cpp -o ..\obj\RTDyldMemoryManager.obj
gpp @a -c src\lib\EE\RuntimeDyld\RuntimeDyld.cpp -o ..\obj\RuntimeDyld.obj
gpp @a -c src\lib\EE\RuntimeDyld\RuntimeDyldChecker.cpp -o ..\obj\RuntimeDyldChecker.obj
gpp @a -c src\lib\EE\RuntimeDyld\RuntimeDyldCOFF.cpp -o ..\obj\RuntimeDyldCOFF.obj
gpp @a -c src\lib\EE\RuntimeDyld\RuntimeDyldELF.cpp -o ..\obj\RuntimeDyldELF.obj
gpp @a -c src\lib\EE\RuntimeDyld\RuntimeDyldMachO.cpp -o ..\obj\RuntimeDyldMachO.obj
gpp @a -c src\lib\EE\SectionMemoryManager.cpp -o ..\obj\SectionMemoryManager.obj
gpp @a -c src\lib\EE\TargetSelect.cpp -o ..\obj\TargetSelect.obj
gpp @a -c src\lib\IR\AsmWriter.cpp -o ..\obj\AsmWriter.obj
gpp @a -c src\lib\IR\Attributes.cpp -o ..\obj\Attributes.obj
gpp @a -c src\lib\IR\AutoUpgrade.cpp -o ..\obj\AutoUpgrade.obj
gpp @a -c src\lib\IR\BasicBlock.cpp -o ..\obj\BasicBlock.obj
gpp @a -c src\lib\IR\Comdat.cpp -o ..\obj\Comdat.obj
gpp @a -c src\lib\IR\ConstantFold.cpp -o ..\obj\ConstantFold.obj
gpp @a -c src\lib\IR\ConstantRange.cpp -o ..\obj\ConstantRange.obj
gpp @a -c src\lib\IR\Constants.cpp -o ..\obj\Constants.obj
gpp @a -c src\lib\IR\Core.cpp -o ..\obj\Core.obj
gpp @a -c src\lib\IR\DataLayout.cpp -o ..\obj\DataLayout.obj
gpp @a -c src\lib\IR\DebugInfo.cpp -o ..\obj\DebugInfo.obj
gpp @a -c src\lib\IR\DebugInfoMetadata.cpp -o ..\obj\DebugInfoMetadata.obj
gpp @a -c src\lib\IR\DebugLoc.cpp -o ..\obj\DebugLoc.obj
gpp @a -c src\lib\IR\DiagnosticInfo.cpp -o ..\obj\DiagnosticInfo.obj
gpp @a -c src\lib\IR\DiagnosticPrinter.cpp -o ..\obj\DiagnosticPrinter.obj
gpp @a -c src\lib\IR\DIBuilder.cpp -o ..\obj\DIBuilder.obj
gpp @a -c src\lib\IR\Dominators.cpp -o ..\obj\Dominators.obj
gpp @a -c src\lib\IR\Function.cpp -o ..\obj\Function.obj
gpp @a -c src\lib\IR\FunctionInfo.cpp -o ..\obj\FunctionInfo.obj
gpp @a -c src\lib\IR\GCOV.cpp -o ..\obj\GCOV.obj
gpp @a -c src\lib\IR\Globals.cpp -o ..\obj\Globals.obj
gpp @a -c src\lib\IR\GVMaterializer.cpp -o ..\obj\GVMaterializer.obj
gpp @a -c src\lib\IR\InlineAsm.cpp -o ..\obj\InlineAsm.obj
gpp @a -c src\lib\IR\Instruction.cpp -o ..\obj\Instruction.obj
gpp @a -c src\lib\IR\Instructions.cpp -o ..\obj\Instructions.obj
gpp @a -c src\lib\IR\IntrinsicInst.cpp -o ..\obj\IntrinsicInst.obj
gpp @a -c src\lib\IR\IRBuilder.cpp -o ..\obj\IRBuilder.obj
gpp @a -c src\lib\IR\IRPrintingPasses.cpp -o ..\obj\IRPrintingPasses.obj
gpp @a -c src\lib\IR\LegacyPassManager.cpp -o ..\obj\LegacyPassManager.obj
gpp @a -c src\lib\IR\LLVMContext.cpp -o ..\obj\LLVMContext.obj
gpp @a -c src\lib\IR\LLVMContextImpl.cpp -o ..\obj\LLVMContextImpl.obj
gpp @a -c src\lib\IR\Mangler.cpp -o ..\obj\Mangler.obj
gpp @a -c src\lib\IR\MDBuilder.cpp -o ..\obj\MDBuilder.obj
gpp @a -c src\lib\IR\Metadata.cpp -o ..\obj\Metadata.obj
gpp @a -c src\lib\IR\Module.cpp -o ..\obj\Module.obj
gpp @a -c src\lib\IR\Operator.cpp -o ..\obj\Operator.obj
gpp @a -c src\lib\IR\Pass.cpp -o ..\obj\Pass.obj
gpp @a -c src\lib\IR\PassManager.cpp -o ..\obj\PassManager.obj
gpp @a -c src\lib\IR\PassRegistry.cpp -o ..\obj\PassRegistry.obj
gpp @a -c src\lib\IR\Statepoint.cpp -o ..\obj\Statepoint.obj
gpp @a -c src\lib\IR\Type.cpp -o ..\obj\Type.obj
gpp @a -c src\lib\IR\TypeFinder.cpp -o ..\obj\TypeFinder.obj
gpp @a -c src\lib\IR\Use.cpp -o ..\obj\Use.obj
gpp @a -c src\lib\IR\User.cpp -o ..\obj\User.obj
gpp @a -c src\lib\IR\Value.cpp -o ..\obj\Value.obj
gpp @a -c src\lib\IR\ValueSymbolTable.cpp -o ..\obj\ValueSymbolTable.obj
gpp @a -c src\lib\IR\ValueTypes.cpp -o ..\obj\ValueTypes.obj
gpp @a -c src\lib\IR\Verifier.cpp -o ..\obj\Verifier.obj
gpp @a -c src\lib\IRReader\IRReader.cpp -o ..\obj\IRReader.obj
gpp @a -c src\lib\Linker\IRMover.cpp -o ..\obj\IRMover.obj
gpp @a -c src\lib\Linker\LinkModules.cpp -o ..\obj\LinkModules.obj
gpp @a -c src\lib\MC\ConstantPools.cpp -o ..\obj\ConstantPools.obj
gpp @a -c src\lib\MC\ELFObjectWriter.cpp -o ..\obj\ELFObjectWriter.obj
gpp @a -c src\lib\MC\MachObjectWriter.cpp -o ..\obj\MachObjectWriter.obj
gpp @a -c src\lib\MC\MCAsmBackend.cpp -o ..\obj\MCAsmBackend.obj
gpp @a -c src\lib\MC\MCAsmInfo.cpp -o ..\obj\MCAsmInfo.obj
gpp @a -c src\lib\MC\MCAsmInfoCOFF.cpp -o ..\obj\MCAsmInfoCOFF.obj
gpp @a -c src\lib\MC\MCAsmInfoDarwin.cpp -o ..\obj\MCAsmInfoDarwin.obj
gpp @a -c src\lib\MC\MCAsmInfoELF.cpp -o ..\obj\MCAsmInfoELF.obj
gpp @a -c src\lib\MC\MCAsmStreamer.cpp -o ..\obj\MCAsmStreamer.obj
gpp @a -c src\lib\MC\MCAssembler.cpp -o ..\obj\MCAssembler.obj
gpp @a -c src\lib\MC\MCCodeEmitter.cpp -o ..\obj\MCCodeEmitter.obj
gpp @a -c src\lib\MC\MCCodeGenInfo.cpp -o ..\obj\MCCodeGenInfo.obj
gpp @a -c src\lib\MC\MCContext.cpp -o ..\obj\MCContext.obj
gpp @a -c src\lib\MC\MCDisassembler\Disassembler.cpp -o ..\obj\Disassembler.obj
gpp @a -c src\lib\MC\MCDisassembler\MCDisassembler.cpp -o ..\obj\MCDisassembler.obj
gpp @a -c src\lib\MC\MCDisassembler\MCExternalSymbolizer.cpp -o ..\obj\MCExternalSymbolizer.obj
gpp @a -c src\lib\MC\MCDisassembler\MCRelocationInfo.cpp -o ..\obj\MCRelocationInfo.obj
gpp @a -c src\lib\MC\MCDwarf.cpp -o ..\obj\MCDwarf.obj
gpp @a -c src\lib\MC\MCELFObjectTargetWriter.cpp -o ..\obj\MCELFObjectTargetWriter.obj
gpp @a -c src\lib\MC\MCELFStreamer.cpp -o ..\obj\MCELFStreamer.obj
gpp @a -c src\lib\MC\MCExpr.cpp -o ..\obj\MCExpr.obj
gpp @a -c src\lib\MC\MCFragment.cpp -o ..\obj\MCFragment.obj
gpp @a -c src\lib\MC\MCInst.cpp -o ..\obj\MCInst.obj
gpp @a -c src\lib\MC\MCInstPrinter.cpp -o ..\obj\MCInstPrinter.obj
gpp @a -c src\lib\MC\MCInstrAnalysis.cpp -o ..\obj\MCInstrAnalysis.obj
gpp @a -c src\lib\MC\MCInstrDesc.cpp -o ..\obj\MCInstrDesc.obj
gpp @a -c src\lib\MC\MCLabel.cpp -o ..\obj\MCLabel.obj
gpp @a -c src\lib\MC\MCLinkerOptimizationHint.cpp -o ..\obj\MCLinkerOptimizationHint.obj
gpp @a -c src\lib\MC\MCMachObjectTargetWriter.cpp -o ..\obj\MCMachObjectTargetWriter.obj
gpp @a -c src\lib\MC\MCMachOStreamer.cpp -o ..\obj\MCMachOStreamer.obj
gpp @a -c src\lib\MC\MCNullStreamer.cpp -o ..\obj\MCNullStreamer.obj
gpp @a -c src\lib\MC\MCObjectFileInfo.cpp -o ..\obj\MCObjectFileInfo.obj
gpp @a -c src\lib\MC\MCObjectStreamer.cpp -o ..\obj\MCObjectStreamer.obj
gpp @a -c src\lib\MC\MCObjectWriter.cpp -o ..\obj\MCObjectWriter.obj
gpp @a -c src\lib\MC\MCParser\AsmLexer.cpp -o ..\obj\AsmLexer.obj
gpp @a -c src\lib\MC\MCParser\AsmParser.cpp -o ..\obj\AsmParser.obj
gpp @a -c src\lib\MC\MCParser\COFFAsmParser.cpp -o ..\obj\COFFAsmParser.obj
gpp @a -c src\lib\MC\MCParser\DarwinAsmParser.cpp -o ..\obj\DarwinAsmParser.obj
gpp @a -c src\lib\MC\MCParser\ELFAsmParser.cpp -o ..\obj\ELFAsmParser.obj
gpp @a -c src\lib\MC\MCParser\MCAsmLexer.cpp -o ..\obj\MCAsmLexer.obj
gpp @a -c src\lib\MC\MCParser\MCAsmParser.cpp -o ..\obj\MCAsmParser.obj
gpp @a -c src\lib\MC\MCParser\MCAsmParserExtension.cpp -o ..\obj\MCAsmParserExtension.obj
gpp @a -c src\lib\MC\MCParser\MCTargetAsmParser.cpp -o ..\obj\MCTargetAsmParser.obj
gpp @a -c src\lib\MC\MCRegisterInfo.cpp -o ..\obj\MCRegisterInfo.obj
gpp @a -c src\lib\MC\MCSchedule.cpp -o ..\obj\MCSchedule.obj
gpp @a -c src\lib\MC\MCSection.cpp -o ..\obj\MCSection.obj
gpp @a -c src\lib\MC\MCSectionCOFF.cpp -o ..\obj\MCSectionCOFF.obj
gpp @a -c src\lib\MC\MCSectionELF.cpp -o ..\obj\MCSectionELF.obj
gpp @a -c src\lib\MC\MCSectionMachO.cpp -o ..\obj\MCSectionMachO.obj
gpp @a -c src\lib\MC\MCStreamer.cpp -o ..\obj\MCStreamer.obj
gpp @a -c src\lib\MC\MCSubtargetInfo.cpp -o ..\obj\MCSubtargetInfo.obj
gpp @a -c src\lib\MC\MCSymbol.cpp -o ..\obj\MCSymbol.obj
gpp @a -c src\lib\MC\MCSymbolELF.cpp -o ..\obj\MCSymbolELF.obj
gpp @a -c src\lib\MC\MCSymbolizer.cpp -o ..\obj\MCSymbolizer.obj
gpp @a -c src\lib\MC\MCTargetOptions.cpp -o ..\obj\MCTargetOptions.obj
gpp @a -c src\lib\MC\MCValue.cpp -o ..\obj\MCValue.obj
gpp @a -c src\lib\MC\MCWin64EH.cpp -o ..\obj\MCWin64EH.obj
gpp @a -c src\lib\MC\MCWinEH.cpp -o ..\obj\MCWinEH.obj
gpp @a -c src\lib\MC\StringTableBuilder.cpp -o ..\obj\StringTableBuilder.obj
gpp @a -c src\lib\MC\SubtargetFeature.cpp -o ..\obj\SubtargetFeature.obj
gpp @a -c src\lib\MC\WinCOFFObjectWriter.cpp -o ..\obj\WinCOFFObjectWriter.obj
gpp @a -c src\lib\MC\WinCOFFStreamer.cpp -o ..\obj\WinCOFFStreamer.obj
gpp @a -c src\lib\MC\YAML.cpp -o ..\obj\YAML.obj
gpp @a -c src\lib\Object\Archive.cpp -o ..\obj\Archive.obj
gpp @a -c src\lib\Object\ArchiveWriter.cpp -o ..\obj\ArchiveWriter.obj
gpp @a -c src\lib\Object\Binary.cpp -o ..\obj\Binary.obj
gpp @a -c src\lib\Object\COFFObjectFile.cpp -o ..\obj\COFFObjectFile.obj
gpp @a -c src\lib\Object\ELF.cpp -o ..\obj\ELF.obj
gpp @a -c src\lib\Object\ELFObjectFile.cpp -o ..\obj\ELFObjectFile.obj
gpp @a -c src\lib\Object\ELFYAML.cpp -o ..\obj\ELFYAML.obj
gpp @a -c src\lib\Object\Error.cpp -o ..\obj\Error.obj
gpp @a -c src\lib\Object\FunctionIndexObjectFile.cpp -o ..\obj\FunctionIndexObjectFile.obj
gpp @a -c src\lib\Object\IRObjectFile.cpp -o ..\obj\IRObjectFile.obj
gpp @a -c src\lib\Object\MachOObjectFile.cpp -o ..\obj\MachOObjectFile.obj
gpp @a -c src\lib\Object\MachOUniversal.cpp -o ..\obj\MachOUniversal.obj
gpp @a -c src\lib\Object\Object.cpp -o ..\obj\Object.obj
gpp @a -c src\lib\Object\ObjectFile.cpp -o ..\obj\ObjectFile.obj
gpp @a -c src\lib\Object\RecordStreamer.cpp -o ..\obj\RecordStreamer.obj
gpp @a -c src\lib\Object\SymbolicFile.cpp -o ..\obj\SymbolicFile.obj
gpp @a -c src\lib\Object\SymbolSize.cpp -o ..\obj\SymbolSize.obj
gpp @a -c src\lib\Option\Arg.cpp -o ..\obj\Arg.obj
gpp @a -c src\lib\Option\ArgList.cpp -o ..\obj\ArgList.obj
gpp @a -c src\lib\Option\Option.cpp -o ..\obj\Option.obj
gpp @a -c src\lib\Option\OptTable.cpp -o ..\obj\OptTable.obj
gpp @a -c src\lib\Passes\PassBuilder.cpp -o ..\obj\PassBuilder.obj
gpp @a -c src\lib\ProfileData\SampleProf.cpp -o ..\obj\SampleProf.obj
gpp @a -c src\lib\ProfileData\SampleProfReader.cpp -o ..\obj\SampleProfReader.obj
gpp @a -c src\lib\ProfileData\SampleProfWriter.cpp -o ..\obj\SampleProfWriter.obj
gpp @a -c src\lib\Support\Allocator.cpp -o ..\obj\Allocator.obj
gpp @a -c src\lib\Support\APFloat.cpp -o ..\obj\APFloat.obj
gpp @a -c src\lib\Support\APInt.cpp -o ..\obj\APInt.obj
gpp @a -c src\lib\Support\APSInt.cpp -o ..\obj\APSInt.obj
gpp @a -c src\lib\Support\ARMBuildAttrs.cpp -o ..\obj\ARMBuildAttrs.obj
gpp @a -c src\lib\Support\ARMWinEH.cpp -o ..\obj\ARMWinEH.obj
gpp @a -c src\lib\Support\Atomic.cpp -o ..\obj\Atomic.obj
gpp @a -c src\lib\Support\BlockFrequency.cpp -o ..\obj\BlockFrequency.obj
gpp @a -c src\lib\Support\BranchProbability.cpp -o ..\obj\BranchProbability.obj
gpp @a -c src\lib\Support\circular_raw_ostream.cpp -o ..\obj\circular_raw_ostream.obj
gpp @a -c src\lib\Support\CommandLine.cpp -o ..\obj\CommandLine.obj
gpp @a -c src\lib\Support\Compression.cpp -o ..\obj\Compression.obj
gpp @a -c src\lib\Support\ConvertUTF.c -o ..\obj\ConvertUTF.obj
gpp @a -c src\lib\Support\ConvertUTFWrapper.cpp -o ..\obj\ConvertUTFWrapper.obj
gpp @a -c src\lib\Support\DAGDeltaAlgorithm.cpp -o ..\obj\DAGDeltaAlgorithm.obj
gpp @a -c src\lib\Support\DataExtractor.cpp -o ..\obj\DataExtractor.obj
gpp @a -c src\lib\Support\DataStream.cpp -o ..\obj\DataStream.obj
gpp @a -c src\lib\Support\Debug.cpp -o ..\obj\Debug.obj
gpp @a -c src\lib\Support\DeltaAlgorithm.cpp -o ..\obj\DeltaAlgorithm.obj
gpp @a -c src\lib\Support\Dwarf.cpp -o ..\obj\Dwarf.obj
gpp @a -c src\lib\Support\DynamicLibrary.cpp -o ..\obj\DynamicLibrary.obj
gpp @a -c src\lib\Support\Errno.cpp -o ..\obj\Errno.obj
gpp @a -c src\lib\Support\ErrorHandling.cpp -o ..\obj\ErrorHandling.obj
gpp @a -c src\lib\Support\FileOutputBuffer.cpp -o ..\obj\FileOutputBuffer.obj
gpp @a -c src\lib\Support\FileUtilities.cpp -o ..\obj\FileUtilities.obj
gpp @a -c src\lib\Support\FoldingSet.cpp -o ..\obj\FoldingSet.obj
gpp @a -c src\lib\Support\FormattedStream.cpp -o ..\obj\FormattedStream.obj
gpp @a -c src\lib\Support\GraphWriter.cpp -o ..\obj\GraphWriter.obj
gpp @a -c src\lib\Support\Hashing.cpp -o ..\obj\Hashing.obj
gpp @a -c src\lib\Support\Host.cpp -o ..\obj\Host.obj
gpp @a -c src\lib\Support\IntEqClasses.cpp -o ..\obj\IntEqClasses.obj
gpp @a -c src\lib\Support\IntervalMap.cpp -o ..\obj\IntervalMap.obj
gpp @a -c src\lib\Support\IntrusiveRefCntPtr.cpp -o ..\obj\IntrusiveRefCntPtr.obj
gpp @a -c src\lib\Support\JamCRC.cpp -o ..\obj\JamCRC.obj
gpp @a -c src\lib\Support\LEB128.cpp -o ..\obj\LEB128.obj
gpp @a -c src\lib\Support\LineIterator.cpp -o ..\obj\LineIterator.obj
gpp @a -c src\lib\Support\Locale.cpp -o ..\obj\Locale.obj
gpp @a -c src\lib\Support\LockFileManager.cpp -o ..\obj\LockFileManager.obj
gpp @a -c src\lib\Support\ManagedStatic.cpp -o ..\obj\ManagedStatic.obj
gpp @a -c src\lib\Support\MathExtras.cpp -o ..\obj\MathExtras.obj
gpp @a -c src\lib\Support\MD5.cpp -o ..\obj\MD5.obj
gpp @a -c src\lib\Support\Memory.cpp -o ..\obj\Memory.obj
gpp @a -c src\lib\Support\MemoryBuffer.cpp -o ..\obj\MemoryBuffer.obj
gpp @a -c src\lib\Support\MemoryObject.cpp -o ..\obj\MemoryObject.obj
gpp @a -c src\lib\Support\Mutex.cpp -o ..\obj\Mutex.obj
gpp @a -c src\lib\Support\Options.cpp -o ..\obj\Options.obj
gpp @a -c src\lib\Support\Path.cpp -o ..\obj\Path.obj
gpp @a -c src\lib\Support\PluginLoader.cpp -o ..\obj\PluginLoader.obj
gpp @a -c src\lib\Support\PrettyStackTrace.cpp -o ..\obj\PrettyStackTrace.obj
gpp @a -c src\lib\Support\Process.cpp -o ..\obj\Process.obj
gpp @a -c src\lib\Support\Program.cpp -o ..\obj\Program.obj
gpp @a -c src\lib\Support\RandomNumberGenerator.cpp -o ..\obj\RandomNumberGenerator.obj
gpp @a -c src\lib\Support\raw_os_ostream.cpp -o ..\obj\raw_os_ostream.obj
gpp @a -c src\lib\Support\raw_ostream.cpp -o ..\obj\raw_ostream.obj
gpp @a -c src\lib\Support\regcomp.c -o ..\obj\regcomp.obj
gpp @a -c src\lib\Support\regerror.c -o ..\obj\regerror.obj
gpp @a -c src\lib\Support\Regex.cpp -o ..\obj\Regex.obj
gpp @a -c src\lib\Support\regexec.c -o ..\obj\regexec.obj
gpp @a -c src\lib\Support\regfree.c -o ..\obj\regfree.obj
gpp @a -c src\lib\Support\regstrlcpy.c -o ..\obj\regstrlcpy.obj
gpp @a -c src\lib\Support\RWMutex.cpp -o ..\obj\RWMutex.obj
gpp @a -c src\lib\Support\ScaledNumber.cpp -o ..\obj\ScaledNumber.obj
gpp @a -c src\lib\Support\SearchForAddressOfSpecialSymbol.cpp -o ..\obj\SearchForAddressOfSpecialSymbol.obj
gpp @a -c src\lib\Support\Signals.cpp -o ..\obj\Signals.obj
gpp @a -c src\lib\Support\SmallPtrSet.cpp -o ..\obj\SmallPtrSet.obj
gpp @a -c src\lib\Support\SmallVector.cpp -o ..\obj\SmallVector.obj
gpp @a -c src\lib\Support\SourceMgr.cpp -o ..\obj\SourceMgr.obj
gpp @a -c src\lib\Support\SpecialCaseList.cpp -o ..\obj\SpecialCaseList.obj
gpp @a -c src\lib\Support\Statistic.cpp -o ..\obj\Statistic.obj
gpp @a -c src\lib\Support\StreamingMemoryObject.cpp -o ..\obj\StreamingMemoryObject.obj
gpp @a -c src\lib\Support\StringExtras.cpp -o ..\obj\StringExtras.obj
gpp @a -c src\lib\Support\StringMap.cpp -o ..\obj\StringMap.obj
gpp @a -c src\lib\Support\StringPool.cpp -o ..\obj\StringPool.obj
gpp @a -c src\lib\Support\StringRef.cpp -o ..\obj\StringRef.obj
gpp @a -c src\lib\Support\StringSaver.cpp -o ..\obj\StringSaver.obj
gpp @a -c src\lib\Support\SystemUtils.cpp -o ..\obj\SystemUtils.obj
gpp @a -c src\lib\Support\TargetParser.cpp -o ..\obj\TargetParser.obj
gpp @a -c src\lib\Support\TargetRegistry.cpp -o ..\obj\TargetRegistry.obj
gpp @a -c src\lib\Support\Threading.cpp -o ..\obj\Threading.obj
gpp @a -c src\lib\Support\ThreadLocal.cpp -o ..\obj\ThreadLocal.obj
gpp @a -c src\lib\Support\Timer.cpp -o ..\obj\Timer.obj
gpp @a -c src\lib\Support\TimeValue.cpp -o ..\obj\TimeValue.obj
gpp @a -c src\lib\Support\ToolOutputFile.cpp -o ..\obj\ToolOutputFile.obj
gpp @a -c src\lib\Support\Triple.cpp -o ..\obj\Triple.obj
gpp @a -c src\lib\Support\Twine.cpp -o ..\obj\Twine.obj
gpp @a -c src\lib\Support\Unicode.cpp -o ..\obj\Unicode.obj
gpp @a -c src\lib\Support\Valgrind.cpp -o ..\obj\Valgrind.obj
gpp @a -c src\lib\Support\Watchdog.cpp -o ..\obj\Watchdog.obj
gpp @a -c src\lib\Support\YAMLParser.cpp -o ..\obj\YAMLParser.obj
gpp @a -c src\lib\Support\YAMLTraits.cpp -o ..\obj\YAMLTraits.obj
gpp @a -c src\lib\Tf\IC\InstCombineAddSub.cpp -o ..\obj\InstCombineAddSub.obj
gpp @a -c src\lib\Tf\IC\InstCombineAndOrXor.cpp -o ..\obj\InstCombineAndOrXor.obj
gpp @a -c src\lib\Tf\IC\InstCombineCalls.cpp -o ..\obj\InstCombineCalls.obj
gpp @a -c src\lib\Tf\IC\InstCombineCasts.cpp -o ..\obj\InstCombineCasts.obj
gpp @a -c src\lib\Tf\IC\InstCombineCompares.cpp -o ..\obj\InstCombineCompares.obj
gpp @a -c src\lib\Tf\IC\InstCombineLoadStoreAlloca.cpp -o ..\obj\InstCombineLoadStoreAlloca.obj
gpp @a -c src\lib\Tf\IC\InstCombineMulDivRem.cpp -o ..\obj\InstCombineMulDivRem.obj
gpp @a -c src\lib\Tf\IC\InstCombinePHI.cpp -o ..\obj\InstCombinePHI.obj
gpp @a -c src\lib\Tf\IC\InstCombineSelect.cpp -o ..\obj\InstCombineSelect.obj
gpp @a -c src\lib\Tf\IC\InstCombineShifts.cpp -o ..\obj\InstCombineShifts.obj
gpp @a -c src\lib\Tf\IC\InstCombineSimplifyDemanded.cpp -o ..\obj\InstCombineSimplifyDemanded.obj
gpp @a -c src\lib\Tf\IC\InstCombineVectorOps.cpp -o ..\obj\InstCombineVectorOps.obj
gpp @a -c src\lib\Tf\IC\InstructionCombining.cpp -o ..\obj\InstructionCombining.obj
gpp @a -c src\lib\Tf\Ins\AddressSanitizer.cpp -o ..\obj\AddressSanitizer.obj
gpp @a -c src\lib\Tf\Ins\BoundsChecking.cpp -o ..\obj\BoundsChecking.obj
gpp @a -c src\lib\Tf\Ins\DataFlowSanitizer.cpp -o ..\obj\DataFlowSanitizer.obj
gpp @a -c src\lib\Tf\Ins\GCOVProfiling.cpp -o ..\obj\GCOVProfiling.obj
gpp @a -c src\lib\Tf\Ins\InstrProfiling.cpp -o ..\obj\InstrProfiling.obj
gpp @a -c src\lib\Tf\Ins\MemorySanitizer.cpp -o ..\obj\MemorySanitizer.obj
gpp @a -c src\lib\Tf\Ins\SafeStack.cpp -o ..\obj\SafeStack.obj
gpp @a -c src\lib\Tf\Ins\ThreadSanitizer.cpp -o ..\obj\ThreadSanitizer.obj
gpp @a -c src\lib\Tf\IPO\ArgumentPromotion.cpp -o ..\obj\ArgumentPromotion.obj
gpp @a -c src\lib\Tf\IPO\BarrierNoopPass.cpp -o ..\obj\BarrierNoopPass.obj
gpp @a -c src\lib\Tf\IPO\ConstantMerge.cpp -o ..\obj\ConstantMerge.obj
gpp @a -c src\lib\Tf\IPO\CrossDSOCFI.cpp -o ..\obj\CrossDSOCFI.obj
gpp @a -c src\lib\Tf\IPO\DeadArgumentElimination.cpp -o ..\obj\DeadArgumentElimination.obj
gpp @a -c src\lib\Tf\IPO\ElimAvailExtern.cpp -o ..\obj\ElimAvailExtern.obj
gpp @a -c src\lib\Tf\IPO\ExtractGV.cpp -o ..\obj\ExtractGV.obj
gpp @a -c src\lib\Tf\IPO\ForceFunctionAttrs.cpp -o ..\obj\ForceFunctionAttrs.obj
gpp @a -c src\lib\Tf\IPO\FunctionAttrs.cpp -o ..\obj\FunctionAttrs.obj
gpp @a -c src\lib\Tf\IPO\FunctionImport.cpp -o ..\obj\FunctionImport.obj
gpp @a -c src\lib\Tf\IPO\GlobalDCE.cpp -o ..\obj\GlobalDCE.obj
gpp @a -c src\lib\Tf\IPO\GlobalOpt.cpp -o ..\obj\GlobalOpt.obj
gpp @a -c src\lib\Tf\IPO\InferFunctionAttrs.cpp -o ..\obj\InferFunctionAttrs.obj
gpp @a -c src\lib\Tf\IPO\InlineAlways.cpp -o ..\obj\InlineAlways.obj
gpp @a -c src\lib\Tf\IPO\Inliner.cpp -o ..\obj\Inliner.obj
gpp @a -c src\lib\Tf\IPO\InlineSimple.cpp -o ..\obj\InlineSimple.obj
gpp @a -c src\lib\Tf\IPO\Internalize.cpp -o ..\obj\Internalize.obj
gpp @a -c src\lib\Tf\IPO\IPConstantPropagation.cpp -o ..\obj\IPConstantPropagation.obj
gpp @a -c src\lib\Tf\IPO\IPO.cpp -o ..\obj\IPO.obj
gpp @a -c src\lib\Tf\IPO\LoopExtractor.cpp -o ..\obj\LoopExtractor.obj
gpp @a -c src\lib\Tf\IPO\LowerBitSets.cpp -o ..\obj\LowerBitSets.obj
gpp @a -c src\lib\Tf\IPO\MergeFunctions.cpp -o ..\obj\MergeFunctions.obj
gpp @a -c src\lib\Tf\IPO\PartialInlining.cpp -o ..\obj\PartialInlining.obj
gpp @a -c src\lib\Tf\IPO\PassManagerBuilder.cpp -o ..\obj\PassManagerBuilder.obj
gpp @a -c src\lib\Tf\IPO\PruneEH.cpp -o ..\obj\PruneEH.obj
gpp @a -c src\lib\Tf\IPO\SampleProfile.cpp -o ..\obj\SampleProfile.obj
gpp @a -c src\lib\Tf\IPO\StripDeadPrototypes.cpp -o ..\obj\StripDeadPrototypes.obj
gpp @a -c src\lib\Tf\IPO\StripSymbols.cpp -o ..\obj\StripSymbols.obj
gpp @a -c src\lib\Tf\OC\DependencyAnalysis.cpp -o ..\obj\DependencyAnalysis.obj
gpp @a -c src\lib\Tf\OC\ObjCARC.cpp -o ..\obj\ObjCARC.obj
gpp @a -c src\lib\Tf\OC\ObjCARCAPElim.cpp -o ..\obj\ObjCARCAPElim.obj
gpp @a -c src\lib\Tf\OC\ObjCARCContract.cpp -o ..\obj\ObjCARCContract.obj
gpp @a -c src\lib\Tf\OC\ObjCARCExpand.cpp -o ..\obj\ObjCARCExpand.obj
gpp @a -c src\lib\Tf\OC\ObjCARCOpts.cpp -o ..\obj\ObjCARCOpts.obj
gpp @a -c src\lib\Tf\OC\ProvenanceAnalysis.cpp -o ..\obj\ProvenanceAnalysis.obj
gpp @a -c src\lib\Tf\OC\ProvenanceAnalysisEvaluator.cpp -o ..\obj\ProvenanceAnalysisEvaluator.obj
gpp @a -c src\lib\Tf\OC\PtrState.cpp -o ..\obj\PtrState.obj
gpp @a -c src\lib\Tf\Scalar\ADCE.cpp -o ..\obj\ADCE.obj
gpp @a -c src\lib\Tf\Scalar\AlignmentFromAssumptions.cpp -o ..\obj\AlignmentFromAssumptions.obj
gpp @a -c src\lib\Tf\Scalar\BDCE.cpp -o ..\obj\BDCE.obj
gpp @a -c src\lib\Tf\Scalar\ConstantHoisting.cpp -o ..\obj\ConstantHoisting.obj
gpp @a -c src\lib\Tf\Scalar\ConstantProp.cpp -o ..\obj\ConstantProp.obj
gpp @a -c src\lib\Tf\Scalar\CorrelatedValuePropagation.cpp -o ..\obj\CorrelatedValuePropagation.obj
gpp @a -c src\lib\Tf\Scalar\DCE.cpp -o ..\obj\DCE.obj
gpp @a -c src\lib\Tf\Scalar\DeadStoreElimination.cpp -o ..\obj\DeadStoreElimination.obj
gpp @a -c src\lib\Tf\Scalar\EarlyCSE.cpp -o ..\obj\EarlyCSE.obj
gpp @a -c src\lib\Tf\Scalar\FlattenCFGPass.cpp -o ..\obj\FlattenCFGPass.obj
gpp @a -c src\lib\Tf\Scalar\Float2Int.cpp -o ..\obj\Float2Int.obj
gpp @a -c src\lib\Tf\Scalar\GVN.cpp -o ..\obj\GVN.obj
gpp @a -c src\lib\Tf\Scalar\InductiveRangeCheckElimination.cpp -o ..\obj\InductiveRangeCheckElimination.obj
gpp @a -c src\lib\Tf\Scalar\IndVarSimplify.cpp -o ..\obj\IndVarSimplify.obj
gpp @a -c src\lib\Tf\Scalar\JumpThreading.cpp -o ..\obj\JumpThreading.obj
gpp @a -c src\lib\Tf\Scalar\LICM.cpp -o ..\obj\LICM.obj
gpp @a -c src\lib\Tf\Scalar\LoadCombine.cpp -o ..\obj\LoadCombine.obj
gpp @a -c src\lib\Tf\Scalar\LoopDeletion.cpp -o ..\obj\LoopDeletion.obj
gpp @a -c src\lib\Tf\Scalar\LoopDistribute.cpp -o ..\obj\LoopDistribute.obj
gpp @a -c src\lib\Tf\Scalar\LoopIdiomRecognize.cpp -o ..\obj\LoopIdiomRecognize.obj
gpp @a -c src\lib\Tf\Scalar\LoopInstSimplify.cpp -o ..\obj\LoopInstSimplify.obj
gpp @a -c src\lib\Tf\Scalar\LoopInterchange.cpp -o ..\obj\LoopInterchange.obj
gpp @a -c src\lib\Tf\Scalar\LoopLoadElimination.cpp -o ..\obj\LoopLoadElimination.obj
gpp @a -c src\lib\Tf\Scalar\LoopRerollPass.cpp -o ..\obj\LoopRerollPass.obj
gpp @a -c src\lib\Tf\Scalar\LoopRotation.cpp -o ..\obj\LoopRotation.obj
gpp @a -c src\lib\Tf\Scalar\LoopStrengthReduce.cpp -o ..\obj\LoopStrengthReduce.obj
gpp @a -c src\lib\Tf\Scalar\LoopUnrollPass.cpp -o ..\obj\LoopUnrollPass.obj
gpp @a -c src\lib\Tf\Scalar\LoopUnswitch.cpp -o ..\obj\LoopUnswitch.obj
gpp @a -c src\lib\Tf\Scalar\LowerAtomic.cpp -o ..\obj\LowerAtomic.obj
gpp @a -c src\lib\Tf\Scalar\LowerExpectIntrinsic.cpp -o ..\obj\LowerExpectIntrinsic.obj
gpp @a -c src\lib\Tf\Scalar\MemCpyOptimizer.cpp -o ..\obj\MemCpyOptimizer.obj
gpp @a -c src\lib\Tf\Scalar\MergedLoadStoreMotion.cpp -o ..\obj\MergedLoadStoreMotion.obj
gpp @a -c src\lib\Tf\Scalar\NaryReassociate.cpp -o ..\obj\NaryReassociate.obj
gpp @a -c src\lib\Tf\Scalar\PartiallyInlineLibCalls.cpp -o ..\obj\PartiallyInlineLibCalls.obj
gpp @a -c src\lib\Tf\Scalar\PlaceSafepoints.cpp -o ..\obj\PlaceSafepoints.obj
gpp @a -c src\lib\Tf\Scalar\Reassociate.cpp -o ..\obj\Reassociate.obj
gpp @a -c src\lib\Tf\Scalar\Reg2Mem.cpp -o ..\obj\Reg2Mem.obj
gpp @a -c src\lib\Tf\Scalar\RewriteStatepointsForGC.cpp -o ..\obj\RewriteStatepointsForGC.obj
gpp @a -c src\lib\Tf\Scalar\Scalar.cpp -o ..\obj\Scalar.obj
gpp @a -c src\lib\Tf\Scalar\Scalarizer.cpp -o ..\obj\Scalarizer.obj
gpp @a -c src\lib\Tf\Scalar\ScalarReplAggregates.cpp -o ..\obj\ScalarReplAggregates.obj
gpp @a -c src\lib\Tf\Scalar\SCCP.cpp -o ..\obj\SCCP.obj
gpp @a -c src\lib\Tf\Scalar\SeparateConstOffsetFromGEP.cpp -o ..\obj\SeparateConstOffsetFromGEP.obj
gpp @a -c src\lib\Tf\Scalar\SimplifyCFGPass.cpp -o ..\obj\SimplifyCFGPass.obj
gpp @a -c src\lib\Tf\Scalar\Sink.cpp -o ..\obj\Sink.obj
gpp @a -c src\lib\Tf\Scalar\SpeculativeExecution.cpp -o ..\obj\SpeculativeExecution.obj
gpp @a -c src\lib\Tf\Scalar\SROA.cpp -o ..\obj\SROA.obj
gpp @a -c src\lib\Tf\Scalar\StraightLineStrengthReduce.cpp -o ..\obj\StraightLineStrengthReduce.obj
gpp @a -c src\lib\Tf\Scalar\StructurizeCFG.cpp -o ..\obj\StructurizeCFG.obj
gpp @a -c src\lib\Tf\Scalar\TailRecursionElimination.cpp -o ..\obj\TailRecursionElimination.obj
gpp @a -c src\lib\Tf\Utils\AddDiscriminators.cpp -o ..\obj\AddDiscriminators.obj
gpp @a -c src\lib\Tf\Utils\ASanStackFrameLayout.cpp -o ..\obj\ASanStackFrameLayout.obj
gpp @a -c src\lib\Tf\Utils\BasicBlockUtils.cpp -o ..\obj\BasicBlockUtils.obj
gpp @a -c src\lib\Tf\Utils\BreakCriticalEdges.cpp -o ..\obj\BreakCriticalEdges.obj
gpp @a -c src\lib\Tf\Utils\BuildLibCalls.cpp -o ..\obj\BuildLibCalls.obj
gpp @a -c src\lib\Tf\Utils\BypassSlowDivision.cpp -o ..\obj\BypassSlowDivision.obj
gpp @a -c src\lib\Tf\Utils\CloneFunction.cpp -o ..\obj\CloneFunction.obj
gpp @a -c src\lib\Tf\Utils\CloneModule.cpp -o ..\obj\CloneModule.obj
gpp @a -c src\lib\Tf\Utils\CmpInstAnalysis.cpp -o ..\obj\CmpInstAnalysis.obj
gpp @a -c src\lib\Tf\Utils\CodeExtractor.cpp -o ..\obj\CodeExtractor.obj
gpp @a -c src\lib\Tf\Utils\CtorUtils.cpp -o ..\obj\CtorUtils.obj
gpp @a -c src\lib\Tf\Utils\DemoteRegToStack.cpp -o ..\obj\DemoteRegToStack.obj
gpp @a -c src\lib\Tf\Utils\FlattenCFG.cpp -o ..\obj\FlattenCFG.obj
gpp @a -c src\lib\Tf\Utils\GlobalStatus.cpp -o ..\obj\GlobalStatus.obj
gpp @a -c src\lib\Tf\Utils\InlineFunction.cpp -o ..\obj\InlineFunction.obj
gpp @a -c src\lib\Tf\Utils\InstructionNamer.cpp -o ..\obj\InstructionNamer.obj
gpp @a -c src\lib\Tf\Utils\IntegerDivision.cpp -o ..\obj\IntegerDivision.obj
gpp @a -c src\lib\Tf\Utils\LCSSA.cpp -o ..\obj\LCSSA.obj
gpp @a -c src\lib\Tf\Utils\Local.cpp -o ..\obj\Local.obj
gpp @a -c src\lib\Tf\Utils\LoopSimplify.cpp -o ..\obj\LoopSimplify.obj
gpp @a -c src\lib\Tf\Utils\LoopUnroll.cpp -o ..\obj\LoopUnroll.obj
gpp @a -c src\lib\Tf\Utils\LoopUnrollRuntime.cpp -o ..\obj\LoopUnrollRuntime.obj
gpp @a -c src\lib\Tf\Utils\LoopUtils.cpp -o ..\obj\LoopUtils.obj
gpp @a -c src\lib\Tf\Utils\LoopVersioning.cpp -o ..\obj\LoopVersioning.obj
gpp @a -c src\lib\Tf\Utils\LowerInvoke.cpp -o ..\obj\LowerInvoke.obj
gpp @a -c src\lib\Tf\Utils\LowerSwitch.cpp -o ..\obj\LowerSwitch.obj
gpp @a -c src\lib\Tf\Utils\Mem2Reg.cpp -o ..\obj\Mem2Reg.obj
gpp @a -c src\lib\Tf\Utils\MetaRenamer.cpp -o ..\obj\MetaRenamer.obj
gpp @a -c src\lib\Tf\Utils\ModuleUtils.cpp -o ..\obj\ModuleUtils.obj
gpp @a -c src\lib\Tf\Utils\PromoteMemoryToRegister.cpp -o ..\obj\PromoteMemoryToRegister.obj
gpp @a -c src\lib\Tf\Utils\SimplifyCFG.cpp -o ..\obj\SimplifyCFG.obj
gpp @a -c src\lib\Tf\Utils\SimplifyIndVar.cpp -o ..\obj\SimplifyIndVar.obj
gpp @a -c src\lib\Tf\Utils\SimplifyInstructions.cpp -o ..\obj\SimplifyInstructions.obj
gpp @a -c src\lib\Tf\Utils\SimplifyLibCalls.cpp -o ..\obj\SimplifyLibCalls.obj
gpp @a -c src\lib\Tf\Utils\SplitModule.cpp -o ..\obj\SplitModule.obj
gpp @a -c src\lib\Tf\Utils\SSAUpdater.cpp -o ..\obj\SSAUpdater.obj
gpp @a -c src\lib\Tf\Utils\SymbolRewriter.cpp -o ..\obj\SymbolRewriter.obj
gpp @a -c src\lib\Tf\Utils\UnifyFunctionExitNodes.cpp -o ..\obj\UnifyFunctionExitNodes.obj
gpp @a -c src\lib\Tf\Utils\Utils.cpp -o ..\obj\Utils.obj
gpp @a -c src\lib\Tf\Utils\ValueMapper.cpp -o ..\obj\ValueMapper.obj
gpp @a -c src\lib\Tf\Vec\BBVectorize.cpp -o ..\obj\BBVectorize.obj
gpp @a -c src\lib\Tf\Vec\LoopVectorize.cpp -o ..\obj\LoopVectorize.obj
gpp @a -c src\lib\Tf\Vec\SLPVectorizer.cpp -o ..\obj\SLPVectorizer.obj
gpp @a -c src\lib\Tf\Vec\Vectorize.cpp -o ..\obj\Vectorize.obj
gpp @a -c src\lib\Tg\Target.cpp -o ..\obj\Target.obj
gpp @a -c src\lib\Tg\TargetIntrinsicInfo.cpp -o ..\obj\TargetIntrinsicInfo.obj
gpp @a -c src\lib\Tg\TargetLoweringObjectFile.cpp -o ..\obj\TargetLoweringObjectFile.obj
gpp @a -c src\lib\Tg\TargetMachine.cpp -o ..\obj\TargetMachine.obj
gpp @a -c src\lib\Tg\TargetMachineC.cpp -o ..\obj\TargetMachineC.obj
gpp @a -c src\lib\Tg\TargetRecip.cpp -o ..\obj\TargetRecip.obj
gpp @a -c src\lib\Tg\TargetSubtargetInfo.cpp -o ..\obj\TargetSubtargetInfo.obj
gpp @a -c src\lib\Tg\X86\AsmParser\X86AsmInstrumentation.cpp -o ..\obj\X86AsmInstrumentation.obj
gpp @a -c src\lib\Tg\X86\AsmParser\X86AsmParser.cpp -o ..\obj\X86AsmParser.obj
gpp @a -c src\lib\Tg\X86\Disassembler\X86Disassembler.cpp -o ..\obj\X86Disassembler.obj
gpp @a -c src\lib\Tg\X86\Disassembler\X86DisassemblerDecoder.cpp -o ..\obj\X86DisassemblerDecoder.obj
gpp @a -c src\lib\Tg\X86\InstPrinter\X86ATTInstPrinter.cpp -o ..\obj\X86ATTInstPrinter.obj
gpp @a -c src\lib\Tg\X86\InstPrinter\X86InstComments.cpp -o ..\obj\X86InstComments.obj
gpp @a -c src\lib\Tg\X86\InstPrinter\X86IntelInstPrinter.cpp -o ..\obj\X86IntelInstPrinter.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86AsmBackend.cpp -o ..\obj\X86AsmBackend.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86ELFObjectWriter.cpp -o ..\obj\X86ELFObjectWriter.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86ELFRelocationInfo.cpp -o ..\obj\X86ELFRelocationInfo.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86MachObjectWriter.cpp -o ..\obj\X86MachObjectWriter.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86MachORelocationInfo.cpp -o ..\obj\X86MachORelocationInfo.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86MCAsmInfo.cpp -o ..\obj\X86MCAsmInfo.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86MCCodeEmitter.cpp -o ..\obj\X86MCCodeEmitter.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86MCTargetDesc.cpp -o ..\obj\X86MCTargetDesc.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86WinCOFFObjectWriter.cpp -o ..\obj\X86WinCOFFObjectWriter.obj
gpp @a -c src\lib\Tg\X86\MCTargetDesc\X86WinCOFFStreamer.cpp -o ..\obj\X86WinCOFFStreamer.obj
gpp @a -c src\lib\Tg\X86\TargetInfo\X86TargetInfo.cpp -o ..\obj\X86TargetInfo.obj
gpp @a -c src\lib\Tg\X86\Utils\X86ShuffleDecode.cpp -o ..\obj\X86ShuffleDecode.obj
gpp @a -c src\lib\Tg\X86\X86AsmPrinter.cpp -o ..\obj\X86AsmPrinter.obj
gpp @a -c src\lib\Tg\X86\X86CallFrameOptimization.cpp -o ..\obj\X86CallFrameOptimization.obj
gpp @a -c src\lib\Tg\X86\X86ExpandPseudo.cpp -o ..\obj\X86ExpandPseudo.obj
gpp @a -c src\lib\Tg\X86\X86FastISel.cpp -o ..\obj\X86FastISel.obj
gpp @a -c src\lib\Tg\X86\X86FixupLEAs.cpp -o ..\obj\X86FixupLEAs.obj
gpp @a -c src\lib\Tg\X86\X86FloatingPoint.cpp -o ..\obj\X86FloatingPoint.obj
gpp @a -c src\lib\Tg\X86\X86FrameLowering.cpp -o ..\obj\X86FrameLowering.obj
gpp @a -c src\lib\Tg\X86\X86InstrInfo.cpp -o ..\obj\X86InstrInfo.obj
gpp @a -c src\lib\Tg\X86\X86ISelDAGToDAG.cpp -o ..\obj\X86ISelDAGToDAG.obj
gpp @a -c src\lib\Tg\X86\X86ISelLowering.cpp -o ..\obj\X86ISelLowering.obj
gpp @a -c src\lib\Tg\X86\X86MachineFunctionInfo.cpp -o ..\obj\X86MachineFunctionInfo.obj
gpp @a -c src\lib\Tg\X86\X86MCInstLower.cpp -o ..\obj\X86MCInstLower.obj
gpp @a -c src\lib\Tg\X86\X86OptimizeLEAs.cpp -o ..\obj\X86OptimizeLEAs.obj
gpp @a -c src\lib\Tg\X86\X86PadShortFunction.cpp -o ..\obj\X86PadShortFunction.obj
gpp @a -c src\lib\Tg\X86\X86RegisterInfo.cpp -o ..\obj\X86RegisterInfo.obj
gpp @a -c src\lib\Tg\X86\X86SelectionDAGInfo.cpp -o ..\obj\X86SelectionDAGInfo.obj
gpp @a -c src\lib\Tg\X86\X86ShuffleDecodeConstantPool.cpp -o ..\obj\X86ShuffleDecodeConstantPool.obj
gpp @a -c src\lib\Tg\X86\X86Subtarget.cpp -o ..\obj\X86Subtarget.obj
gpp @a -c src\lib\Tg\X86\X86TargetMachine.cpp -o ..\obj\X86TargetMachine.obj
gpp @a -c src\lib\Tg\X86\X86TargetObjectFile.cpp -o ..\obj\X86TargetObjectFile.obj
gpp @a -c src\lib\Tg\X86\X86TargetTransformInfo.cpp -o ..\obj\X86TargetTransformInfo.obj
gpp @a -c src\lib\Tg\X86\X86VZeroUpper.cpp -o ..\obj\X86VZeroUpper.obj
gpp @a -c src\lib\Tg\X86\X86WinEHState.cpp -o ..\obj\X86WinEHState.obj
pause
