
 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@                                          
 @                                    @.       @.                                
 @                     @#@ @@@  @@@   @.     @@@ @@  @@                          
 @                    @. @ @  @@, @   @.     @.@ @ @ @ .                         
 @                    @    @@@.@      @.    @. @@  @  @                          
 @                    @ @@ @   @ @@   @.     @@, @@.@@@                          
 @                     @. @     @.    @.                                         
 @                                    @.                                         
 @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@   
                                      @  @@   @@   @@                         :. 
                  @@  @@  @@          @ @..@ @..@ @ @.                        :. 
                 @. .@. @@.           @ @, @ @  @ @@                          :. 
                 @. ,@.@.@ @          @ @  @ @  @   @                         :. 
                  @@ @@@  @.          @ @@@  @@@  @@@                         :. 
                     @                @                                       :. 
                                      @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@;. 
                                       ........................................  


  === Vous are connected to the Cpcdos OSx TELNET server ===

